# Generated by Django 3.2.6 on 2021-08-29 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام دسته بندی ')),
                ('price', models.FloatField(verbose_name='قیمت هر واحد (به تومان) ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات دسته بندی')),
            ],
            options={
                'verbose_name': 'دسته بندی اجزا',
                'verbose_name_plural': 'دسته بندی اجزا',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CurrentExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام ')),
                ('cost_in_a_year', models.IntegerField(verbose_name='هزینه در یک سال (به تومان) ')),
            ],
            options={
                'verbose_name': 'هزینه جاری',
                'verbose_name_plural': 'هزینه های جاری',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام محصول ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات محصول')),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='images/product/', verbose_name='تصویر محصول ')),
                ('no_prod_per_year', models.IntegerField(verbose_name='چه تعداد از این محصول در سال تولید می شود')),
                ('components_cost', models.IntegerField(blank=True, default=0, null=True, verbose_name='هزینه ی اجزای تشکیل شده (به تومان) ')),
                ('current_expense', models.IntegerField(blank=True, default=0, null=True, verbose_name='هزینه های جاری برای این محصول (به تومان) ')),
                ('profit_percent', models.IntegerField(blank=True, default=0, null=True, verbose_name='سود این محصول ( به درصد % ) ')),
                ('final_price', models.IntegerField(blank=True, default=0, null=True, verbose_name='قیمت نهایی (به تومان) ')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TutorialVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('video', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='ComponentConstant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات ')),
                ('component_constant_image', models.ImageField(blank=True, null=True, upload_to='images/component_constant/', verbose_name='تصویر اجزا ')),
                ('price', models.FloatField(verbose_name='قیمت ')),
                ('per_product', models.IntegerField(verbose_name='برای چه تعداد از محصول انتخاب شده ')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cost.product', verbose_name='برای چه محصولی است ')),
            ],
            options={
                'verbose_name': 'اجزای ثابت',
                'verbose_name_plural': 'اجزای ثابت',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام این جزء ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات ')),
                ('component_image', models.ImageField(blank=True, null=True, upload_to='images/component/', verbose_name='تصویر اجزا ')),
                ('used_count', models.IntegerField(verbose_name='چه تعداد از این جزء استفاده می شود ')),
                ('per_product', models.IntegerField(verbose_name='برای چه تعداد از محصول انتخاب شده ')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cost.componentcategory', verbose_name='از کدام نوع دسته بندی است ')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cost.product', verbose_name='برای چه محصولی است ')),
            ],
            options={
                'verbose_name': 'اجزا',
                'verbose_name_plural': 'اجزا',
                'ordering': ['id'],
            },
        ),
    ]
