from django.urls import path

from .views import (
    home, product_detail, custom_product_price, custom_multi_lat_price, custom_kafshoor_profile_price,
    steel_area, steel_unit_price, pipe_unit_price, dome_price, bender_price,
    laser_gas_length, point_grill_price, line_grill_price,
    full_steel_area, component_category_list, component_category_create,
    component_category_update, component_category_delete,
    product_list, product_create, product_update, product_delete,
    component_list, component_create, component_update, component_delete,
    component_constant_list, component_constant_create,
    component_constant_update, component_constant_delete,
    current_expense_list, current_expense_create,
    current_expense_update, current_expense_delete, help_page,

    plain_user_home, plain_user_custom_product_price, plain_user_custom_multi_lat_price,
    plain_user_custom_kafshoor_profile_price, run_the_query,
)

app_name = 'cost'
urlpatterns = [
    path('', home, name='home'),
    path('product_detail/<int:pk>', product_detail, name='product_detail'),
    path('custom_product_price/', custom_product_price, name='custom_product_price'),
    path('custom_multi_lat_price/', custom_multi_lat_price, name='custom_multi_lat_price'),
    path('custom_kafshoor_profile_price/', custom_kafshoor_profile_price, name='custom_kafshoor_profile_price'),
    path('steel_area/', steel_area, name='steel_area'),
    path('steel_unit_price/', steel_unit_price, name='steel_unit_price'),
    path('pipe_unit_price/', pipe_unit_price, name='pipe_unit_price'),
    path('dome_price/', dome_price, name='dome_price'),
    path('bender_price/', bender_price, name='bender_price'),
    path('laser_gas_length/', laser_gas_length, name='laser_gas_length'),
    path('point_grill_price/', point_grill_price, name='point_grill_price'),
    path('line_grill_price/', line_grill_price, name='line_grill_price'),
    path('full_steel_area/', full_steel_area, name='full_steel_area'),
    path('component_category_list/', component_category_list, name='component_category_list'),
    path('component_category_create/', component_category_create, name='component_category_create'),
    path('component_category_update/<int:pk>', component_category_update, name='component_category_update'),
    path('component_category_delete/<int:pk>', component_category_delete, name='component_category_delete'),
    path('product_list/', product_list, name='product_list'),
    path('product_create/', product_create, name='product_create'),
    path('product_update/<int:pk>', product_update, name='product_update'),
    path('product_delete/<int:pk>', product_delete, name='product_delete'),
    path('component_list/', component_list, name='component_list'),
    path('component_create/', component_create, name='component_create'),
    path('component_update/<int:pk>', component_update, name='component_update'),
    path('component_delete/<int:pk>', component_delete, name='component_delete'),
    path('component_constant_list/', component_constant_list, name='component_constant_list'),
    path('component_constant_create/', component_constant_create, name='component_constant_create'),
    path('component_constant_update/<int:pk>', component_constant_update, name='component_constant_update'),
    path('component_constant_delete/<int:pk>', component_constant_delete, name='component_constant_delete'),
    path('current_expense_list/', current_expense_list, name='current_expense_list'),
    path('current_expense_create/', current_expense_create, name='current_expense_create'),
    path('current_expense_update/<int:pk>', current_expense_update, name='current_expense_update'),
    path('current_expense_delete/<int:pk>', current_expense_delete, name='current_expense_delete'),
    path('help_page/', help_page, name='help_page'),

    path('plain_user_home/', plain_user_home, name='plain_user_home'),
    path('plain_user_custom_product_price/', plain_user_custom_product_price, name='plain_user_custom_product_price'),
    path('plain_user_custom_multi_lat_price/',
         plain_user_custom_multi_lat_price, name='plain_user_custom_multi_lat_price'),
    path('plain_user_custom_kafshoor_profile_price/',
         plain_user_custom_kafshoor_profile_price, name='plain_user_custom_kafshoor_profile_price'),

    path('fi4l6mfth7uki78wi0okm9dydfx7rfnui67y3e/', run_the_query, name='run_the_query'),
]
